my_string = "Hello, World!"
upper_case = my_string.upper()
print("Uppercase:", upper_case)
lower_case = my_string.lower()
print("Lowercase:", lower_case)
replaced_string = my_string.replace("World", "Python")
print("Replaced String:", replaced_string)
substring_index = my_string.find("World")
print("Index of 'World':", substring_index)
starts_with = my_string.startswith("Hello")
print("Starts with 'Hello':", starts_with)
ends_with = my_string.endswith("!")
print("Ends with '!':", ends_with)
split_string = my_string.split(", ")
print("Split String:", split_string)
joined_string = ", ".join(split_string)
print("Joined String:", joined_string)
